version: 2
jobs:
    dependencies:
        working_directory: ~/project
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Updating npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules

    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:latest
        branches:
            ignore:
                - gh-pages
        steps:
            - run:
                name: Running production build
                command: 'npm run production'

    deploy:
        docker:
            - image: circleci/node:latest
        steps:
            - run:
                name: Deploy gh-pages to Github Pages
                command: './deploy.sh dist'

workflows:
    version: 2
    build-deploy:
        jobs:
        - dependencies
        - build:
            requires:
                - dependencies
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
