version: 2
jobs:
    test:
        docker:
            - image: circleci/node:6-browsers
              environment:
                  CHROME_BIN: "/usr/bin/google-chrome"
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - run:
                name: Installing process-nextick-args
                command: 'npm install -g process-nextick-args'
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Running unit tests
                command: 'yarn test'
            - persist_to_workspace:
                root: .
                paths: .
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - run:
                name: Running production build
                command: 'npm run production'
            - persist_to_workspace:
                root: .
                paths: .
    deploy:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - run:
                name: Build
                command: 'npm run production'
            - deploy:
                name: Deploy gh-pages to Github Pages
                command: './deploy.sh dist'

workflows:
    version: 2
    build-deploy:
        jobs:
        - test:
            filters:
                branches:
                    ignore:
                        - gh-pages
        - build:
            requires:
                - test
            filters:
                branches:
                    ignore:
                        - gh-pages
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
