version: 2
jobs:
    dependencies:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Updating npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - persist_to_workspace:
                root: .
                paths: .
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Updating npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - run:
                name: Running production build
                command: 'npm run production'
            - persist_to_workspace:
                root: .
                paths: .
    deploy:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Updating npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - run:
                name: Build
                command: 'npm run production'
            - deploy:
                name: Deploy gh-pages to Github Pages
                command: './deploy.sh dist'

workflows:
    version: 2
    build-deploy:
        jobs:
        - dependencies
        - build:
            requires:
                - dependencies
            filters:
                branches:
                    ignore:
                        - gh-pages
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
